### ISSUE TITLE
Update default branch to main

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad-ext-nauert#44]
Hi @nivlekp! Would you be interested in updating the name of Nauert's default from 'master' to (the much more neutral-sounding) 'main'? I updated Abjad and the rmakers today, so if you'd like to make the corresponding change, feel free. It's super easy. Just go to ...

https://github.com/Abjad/abjad-ext-nauert/branches

... and click on the icon of the pencil to the right of the default branch. A rename modal is available, and everything works easily.

**Comment by nivlekp** [comment]
That is a great idea, but I don't think I can change it on my end (the pencil icon is not there). I suspect only you can change that, so if you'd like the make the change, please go ahead. Thank you!

**Comment by trevorbaca** [comment]
Ah, ok! Done! To teach your local clone about the name change, go to the front page of the GitHub site, copy the four commands that the page now prompts us with, and paste those into the terminal. (Alternatively, just make a new local clone of the repo.)
